version: "3.9"

services:
  dev:
    build:
      context: .
      target: dev
    stdin_open: true
    tty: true
    entrypoint: []
    command:
      [
        "sh",
        "-c",
        "cp --update /var/lib/poetry/poetry.lock /app/ && mkdir -p /app/.git/hooks/ && cp --update /var/lib/git/* /app/.git/hooks/ && zsh"
      ]
    environment:
      - POETRY_PYPI_TOKEN_PYPI
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    ports:
      - "8000"
    volumes:
      - .:/app/
      - app-env:/opt/app-env/
      - ~/.gitconfig:/etc/gitconfig
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts
      - ${SSH_AGENT_AUTH_SOCK:-/run/host-services/ssh-auth.sock}:/run/host-services/ssh-auth.sock
    profiles:
      - dev
  app:
    build:
      context: .
      target: app
    tty: true
    ports:
      - "8000:8000"

volumes:
  app-env:
